# Generated by Django 2.2 on 2019-10-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
