# Generated by Django 2.2 on 2019-10-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flight_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrival_date',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_date',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_location',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_location',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
