# Generated by Django 2.2 on 2019-10-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_auto_20191016_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='customer',
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
