# Generated by Django 2.2 on 2019-11-05 11:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191104_1336'),
        ('flights', '0006_auto_20191017_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='create_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='published_date',
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_code', models.CharField(default=0, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='flights.Flight')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reservation', to='accounts.Profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
